FROM continuumio/miniconda3  AS python-image


#################################################
# Install minimap
#################################################
WORKDIR /usr/local
RUN git clone https://github.com/lh3/minimap2
WORKDIR /usr/local/minimap2

RUN apt update
RUN apt install build-essential -y --no-install-recommends
RUN apt install make

RUN pwd
RUN git checkout v2.3
RUN make && chmod 777 minimap2

FROM python-image as run-image

COPY --from=build-image . . 
COPY --from=build-image /usr/local/minimap2 .

ENTRYPOINT [ "python", "app.py" ]

